### ISSUE TITLE
Allow compose window in a tab

### ISSUE THREAD

**Issue by dagsoftware** [binaryoutcast/binoc-central#25]
Hello.

I will like to see Write mail in tab, instead of in new window.

Is it possible this option?

**Comment by mattatobin** [comment]
Perhaps.. The main issue is the menubar both in the xul of the compose window and the menu in the three pane window..

It is part of the longer term plan to be able to load most everything in a tab or window on a per component basis with prefs dictating the default action eg via button or double click..

ANYTHING is possible the question is how feasable it is and how much work and time it will take to accomplish.

**Comment by mattatobin** [comment]
The chances of this happening is low until/unless I rework how the main window and tabs work. Still keeping this as Status: Research though..

**Comment by mattatobin** [comment]
IF a major main window rewrite happens we will get this and it will be opened as part of that issue.
