### ISSUE TITLE
intermittent hangs on sending messages

### ISSUE THREAD

**Issue by wolfbeast** [binaryoutcast/binoc-central#30]
I've run into some intermittent hangs on sending messages. Cancelling and trying to send the same message again seems to succeed as a workaround.

Error console:
```
Error: TypeError: can't convert undefined to object
Source File: chrome://messenger/content/msgHdrViewOverlay.js
Line: 1311
```

**Comment by mattatobin** [comment]
Seems to be chuncks of chat code that is left over in a function UpdateEmailNodeDetails.

http://xref.binaryoutcast.com/binoc-central/source/mail/base/content/msgHdrViewOverlay.js#1279

**Comment by mattatobin** [comment]
I hope... :P

**Comment by wolfbeast** [comment]
We've determined that this was interaction with an issue in enigmail.

**Comment by mattatobin** [comment]
Strange bug.. needed both FIXED and INVALID :P
