### ISSUE TITLE
Windows x64 version does not start

### ISSUE THREAD

**Issue by Gittyperson** [binaryoutcast/binoc-central#51]
Uninstalled Interlink unstable (didn't touch the profile), installed the x64 version, it fails to start:

![interlink 64-bit](https://user-images.githubusercontent.com/7165208/49646048-a3496e80-fa26-11e8-96eb-cd9d3731737a.png)

Uninstalled the x64, installed the x86: it works.

W10 1809

**Comment by kn-yami** [comment]
According to Microsoft's [MS-ERREF] this error code "indicates an operation that is incompatible with built-in accounts has been attempted on a built-in (special) SAM account".

**Comment by mattatobin** [comment]
That's odd cause I use the 64bit version my self.. Do you have a processor that has the AVX instruction set?

**Comment by Gittyperson** [comment]
Indeed, no AVX. It's one of [these](https://ark.intel.com/products/codename/26553/Yorkfield).

**Comment by mattatobin** [comment]
You do know I just spent like last hour upgrading my Windows 10 VM just to confirm you did not read the [Interlink System Requirements](http://beta.binaryoutcast.com/projects/interlink/#system-requirements) ...

**Comment by Gittyperson** [comment]
Ok sorry, first time I run into this problem with x64. Guess the hardware is starting to look its age.
