### ISSUE TITLE
Facebook shows ads. EasyList says it's not their problem.

### ISSUE THREAD

**Issue by BenFenner** [binaryoutcast/binoc-central#57]
I've been seeing ads on Facebook for a couple months now.

Browser: Pale Moon (latest)
Adblocker: ABPrime
Ad blocking lists subscriptions: EasyList

I submitted an issue to EasyList, but they are on their high horse.
https://forums.lanik.us/viewtopic.php?p=144193#p144193

Here's an example of what I'm seeing:
https://i.imgur.com/JLrFjdq.png

I'm not sure if there is anything that can be done. But I would appreciate any help I can get.
I've tried to label this for ABPrime, but that must be up to you Tobin.

**Comment by mattatobin** [comment]
Have you tried simply using Fanboy's Social Blocking List?

**Comment by BenFenner** [comment]
I added that list last night. Restarted the browser, and looked for ads on Facebook. Eventually this morning I ran across another in-feed ad similar to in the screenshot.
There may be less ads now? But they are still appearing.

**Comment by mattatobin** [comment]
I don't know what you want me to do about it. You will just have to debug facebook and create and find some compatible filters or help by adding new filter features.

**Comment by mattatobin** [comment]
A good question is does Adblock Latitude support those newer filters? Cause I was thinking that I might actually take ABL's technology and make it toolkit as a new version of ABPrime.

**Comment by BenFenner** [comment]
I will test and report back.

**Comment by BenFenner** [comment]
I uninstalled ABPrime, restarted the browser, then installed AdBlock Latitude. It picked up the same filters I had before (EasyList, Fanboy's Social Blocking List, and Adblock Warning Removal List), which I made sure to then check for updates.

I can confirm that the Facebook ads still exist, just the same as with ABPrime.

**Comment by mattatobin** [comment]
Hmm. Well thanks for testing.

**Comment by Ligge** [comment]
For what it's worth, Facebook is playing a cat and mouse game with adblockers in general anyway, as reported on last month by BBC News.

https://www.bbc.com/news/technology-46508234

So I'd say it's not the fault of the adblocker, I'd put it more in the territory of lists needing to be updated to combat Facebook's latest version of the ads.

Although I have no idea whether list subscription maintainers are keeping track of it as closely as those at uBlock (as reported in the above BBC News link).
