### ISSUE TITLE
Remove user-agent headers

### ISSUE THREAD

**Issue by Marcosdw** [binaryoutcast/binoc-central#62]
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:60.9) Goanna/4.1 Interlink/52.9.6922

Fix remove temporaly:

To disable the "User-Agent" header, follow these steps:

    In the main menu, select "Preferences" to open the preferences dialog.
    Select the "Advanced" section in the top tool bar.
    Select the "General" tab.
    Click the "Config Editor" button in the lower right to open the configuration editor dialog. It will give you a warning about potentially breaking things, just click the button labeled "I'll be careful, I promise!".
    Anywhere in the list of configuration settings, right-click and select "New" > "String" to create a new setting.
    You will be asked to enter the new preference name, enter: "general.useragent.override" and click the "Ok" button.
    You will be asked to enter a value, leave it empty and click the "Ok" button.

What you just did was tell Thunderbird that you want override the value of the "User-Agent" header in emails. By leaving the value blank, Thunderbird will not add the "User-Agent" header to emails at all.

Or

create file name : user.js in profile Interlink directory add this: 

user_pref("general.useragent.override", "");

Save and exit

Please, fix in the next release.

Thank's 

Marco
___

**Comment by kn-yami** [comment]
But what do you want to fix?

**Comment by mattatobin** [comment]
I don't understand what you are asking for here.
