### ISSUE TITLE
Interlink Add-ons Manager not complete

### ISSUE THREAD

**Issue by Ideficks** [binaryoutcast/binoc-central#64]
Interlink's Interlink Add-ons Manager can't search for add-ons on https://addons.thunderbird.net as FossaMail can. 
In Interlink you can indeed read "Search all add-ons" in the search box. But when I type e.g. the word "about" in the box and enter search it tells me only "Could not find any matching add-ons". In FossaMail it shows a list of compatible add-ons from addons.thunderbird.net.
Also the item "Get Add-ons" isn't shown in Interlink's Add-ons Manager.
Interlink addon-manager: https://i.imgur.com/rXac9Bw.jpg
FossaMail addon-manager: https://i.imgur.com/LElLv2L.jpg

**Comment by kn-yami** [comment]
AFAIK Interlink AM will never be able to search add-ons from AMO, instead it will have its own add-on portal.
