### ISSUE TITLE
Do you still plan to make a new version of the Borealis Navigator?

### ISSUE THREAD

**Issue by FrostKnight** [binaryoutcast/binoc-central#67]
I read it says its a personal project of yours, but I wondered, it looks very interesting... would you be willing to post your source even if its at a "you are on your own!" basis? next to the interlink?

IF we wanted to use said navigator I mean.  

I literally suggested to some developers (Hyperbola) that they should do exactly what you plan to do or have already started doing.

Anyhow, let me know your answer. 

 Either way, The idea behind it sounds very lightweight and I bet it supports the seamonkey addons that deal with the web part, not the email part which you ripped out.

**Comment by mattatobin** [comment]
It is not SeaMonkey and will not support unmodifed extensions.. The source is in this repository and if you ARE looking at the commits you can see it has been getting some work done here and there when I have time to squeeze it in..

It is however not ready for the public and hasn't yet been fully rebranded there are still SeaMonkey assets floating about..

I expect to finish an initial release later this year but again I must stress that it is not SeaMonkey without mailnews and composer.. It is more than that and is already structurally different from it with more to change.

I don't play that fork but keep it virtually identical game.. If I did that, why bother.

**Comment by FrostKnight** [comment]
I think if you tried to keep it virtually identical it would be very cool and if it had compatibility with seamonkey addons, even cooler.  But if that's not something you want, I will look elsewhere, still, I would love such an idea.  If you change your mind let me know.

**Comment by mattatobin** [comment]
I just want to build my dream Navigator that I have always wanted. Of course it has a Communicator bias as that is pretty close to what I think a browser should be but it doesn't have to be limited to SeaMonkey to be cool.. Not like SeaMonkey in a lot of ways stayed true to Netscape even though they initially tried and superficially claimed to be when it was obvious it wasn't.

**Comment by FrostKnight** [comment]
I wasn't condemning it, just saying, it could be so much more.  Seamonkey fork with only the navigator part + addon functionality of seamonkey for the web browsing part sounds way more awesome.  :)  But yeah, I will check it out anyways.  Even the way you intend to make it looks lovely.   My only gripe would be the lack of certain addon compatibility.  
Anywho, thanks for inspiring me.

**Comment by mattatobin** [comment]
What extensions are you wanting?

**Comment by FrostKnight** [comment]
It doesn't matter, as I know you are not fond of noscript. ;)
That, greasemonkey and ublock origin.  my point though I guess is, your fine just enjoy your browser. 
I am hopeful someday someone will do the exact thing I tried to ask you.  Feel free to close completely if you want.  This thread has served its purpose indeed.

**Comment by mattatobin** [comment]
There is little demand for the communicator code. If you want those undesirable extensions.. Then fork or convince them to support the navigator when it is released.

**Comment by FrostKnight** [comment]
That's fine, I may have to wait a while if that's the case. But I am curious, why you consider that extension undesirable. It always works just fine for me. There is an enable all globally dangerous option for those whom it would annoy. My mother has it, noscript, in her firefox and she isn't technically literate yet, it mostly doesn't bother her.  Especially now that no videos are blocked by default.
Regardless, surprising the communicator code isn't more wanted.
