### ISSUE TITLE
Interlink theme

### ISSUE THREAD

**Issue by WalrusInAnus** [binaryoutcast/binoc-central#68]
After the latest update, the theme completely changed, and the program suddenly looks pretty damn ugly.
I don't really understand what happen there :(

**Comment by mattatobin** [comment]
What theme? Nothing has changed in the theme.

Why would you not have included a screenshot?

**Comment by WalrusInAnus** [comment]
Uh, sorry, no coffee.
I also only installed the thing like two days ago.
![untitled](https://user-images.githubusercontent.com/17233430/53175333-08efd480-35ec-11e9-85d0-9982d297b63d.png)
This is what Interlink looks like after the update I got yesterday.

**Comment by mattatobin** [comment]
And what is the issue?

**Comment by WalrusInAnus** [comment]
> 
> 
> And what is the issue?

It looks different than before the update.
I thought it wasn't supposed to.

**Comment by mattatobin** [comment]
Well i have no idea what you are talking about since there is only one other theme that is compatible with Interlink besides the default toolkit style which you are obviously using now..

You do know thunderbird themes are NOT compatible right?

**Comment by WalrusInAnus** [comment]
I have no idea what am I talking about either.
All I know is I installed Interlink, two days later it got an update, and now it looks completely different.
Saying I am confused is an understatement.

**Comment by mattatobin** [comment]
Did you copy a profile or something?

**Comment by WalrusInAnus** [comment]
Aha! Yes. Can that be related?

**Comment by mattatobin** [comment]
Migrated profiles with enabled themes somethimes don't get reeval'd until a version bump cause it was already in place. Whatever Thunderbird theme you were using was reeval'd as not compatible when it updated...

Since there had been major structual changes to messenger.xul during initial development, I am surprised the Thunderbird Theme wasn't noticeably busted before that.

Look in your Add-ons Manager.. What theme was it and version.

**Comment by WalrusInAnus** [comment]
Ignore Aero. No idea about version, but seemingly not updated since 2017.
I guess that's the whole problem...

**Comment by kn-yami** [comment]
I guess it was this one: https://addons.thunderbird.net/en-us/thunderbird/addon/ignore-aero/.

**Comment by mattatobin** [comment]
Well, you are seeing the true default theme now.. It is designed to blend in with the OS.

Can't blame me that Windows 8+ design is lifeless :P

**Comment by mattatobin** [comment]
One can hope that people port or make other themes that aren't as souless in the future.

**Comment by WalrusInAnus** [comment]
Righ :)
Thanks for clarification.
