### ISSUE TITLE
Non-free software add-ons

### ISSUE THREAD

**Issue by swedebugia** [binaryoutcast/binoc-central#72]
Hi
I would like to package interlink in Guix which is a GNU distribution following the FSDG.
Going through the add-ons here: http://interlink-addons.binaryoutcast.com/extensions/ I found 4 non-free ones:
- kakusu
- quickfolders
- fireshot
- isadmin

Would you be willing to remove those from the website?

**Comment by mattatobin** [comment]
That would be a no. Additionally, Interlink branding is trademark and copyrighted maternal and you may not distribute a branded build of it.

**Comment by swedebugia** [comment]
Ok, thanks for the information. We will then have to debrand it to something like Newlink (Newmoon being a debranding of Pale Moon under way into Guix).

**Comment by mattatobin** [comment]
The source has generic branding in the source you can use.
