### ISSUE TITLE
Interlink code change availability?

### ISSUE THREAD

**Issue by 0strodamus** [binaryoutcast/binoc-central#73]
Now that the repo here appears to have been cleared, is there anywhere else to view code changes?

**Comment by kn-yami** [comment]
Currently you can only get source code for released versions, available here: http://binaryoutcast.com/projects/interlink/.

**Comment by mattatobin** [comment]
This is in a response to Roytam1 and his borderline (and when it comes to the navigator) illegal builds he is distributing.

Until/unless he removes the offending navigator builds and stops directly referring to his builds by BinOC Trademarked names and issues a direct disclaimer that his builds are in no way affiliated with Binary Outcast and acknowledging the rights to the trademarks he is using either directly in the binaries or causally in reference. The GIT Repository will remain private and off of GitHub.

He has been operating with impunity for too long as it is and he is directly responsible for this decision having to be made.

The MPL will be satisfied in any event. For currently released builds, `Source Code Form` is being linked from the Interlink page on the BinOC website. Upon the next version of Interlink the new policy will be implemented which will inform recipients of the `Executable Form` will be informed how they may obtain the `Source Code Form` It will also include the hinted at but not directly stated license regarding the distribution of the `Executable Form`.

I did not want it to come to this but they forced my hand when they disrespected my rights in this matter. I expected this but hoped it wouldn't.

I am sorry for the inconvenience this all causes.

**Comment by wolfbeast** [comment]
As a point of note: if similar non-fair-use of Pale Moon, Basilisk and other trademarks of Moonchild Productions are being used and this is made known to me, I may consider similar changes in the future.

Please see http://www.palemoon.org/branding.shtml with clear examples of DO and DON'T that has been posted for years. If your product is not an official build or endorsed build, then do not refer to it as being a product with the trademarked/branded name.

**Comment by 0strodamus** [comment]
That sucks for me as an end-user, but I do understand your concerns. Thanks for the response.

**Comment by mattatobin** [comment]
@0strodamus What do you specifically need?

**Comment by 0strodamus** [comment]
I like following the commit log for 2 reasons. One is that it is educational (and sometimes entertaining depending on your commit comments, for example the close buttons in Linux commit) and the second is to see what has changed that may affect my personal builds.

This is a moot point because you backed out the change, but one example would be when you added enigmail as a bundled extension. I was planning to unbundle it and keep it as a separate extension.
Another more current example would be the removal of the calendar directory. I didn't notice it missing in the 7z source, but would have noticed the commit. I could have acquired the directory from the prior release and saved the time I wasted when my initial build failed part-way through. (And yes, I know the calendar isn't supported and may break at any time, but I like building it as long as it continues to work.)

I'm not sure how you could accommodate me specifically while keeping the commit log hidden from public view, but maybe there is a way.

I also should add that I don't understand how removing the github commits and tarballs while still offering the source code as a 7z download prevents this Roytam1 character from continuing to release illegal builds. Is it because you can block his IP address from your binoc servers?

**Comment by roytam1** [comment]
> Until/unless he removes the offending navigator builds and stops directly referring to his builds by BinOC Trademarked

I think I'm now corrected the issue and hope this repo will be in public again.

**Comment by mattatobin** [comment]
Thank you, @roytam1 I will get it shifted back soon.

I believe Moonchild wants the same thing re:reference wise.

**Comment by 0strodamus** [comment]
Thanks guys!
