### ISSUE TITLE
7z source scripts not executable in Linux 

### ISSUE THREAD

**Issue by 0strodamus** [binaryoutcast/binoc-central#75]
6990 7z source scripts are no longer executable in Linux like they were when hosted here.

**Comment by mattatobin** [comment]
Blame illegal builds by Roytam for this. Not me. The MPL doesn't care if the exec permissions are not preserved, btw.

**Comment by mattatobin** [comment]
I will be recapturing the source matching release versions on linux when I get a chance. The 7zip archives were put up due to the change to satisfy current MPL requirements.

**Comment by 0strodamus** [comment]
Thanks for reconsidering this. I appreciate it.

**Comment by mattatobin** [comment]
No problem, just irked by the situation is all.

**Comment by 0strodamus** [comment]
I understand.

**Comment by mattatobin** [comment]
This is fixed btw... See the FAQ on the page.
