### ISSUE TITLE
Add-on Update not picking up latest version

### ISSUE THREAD

**Issue by RealRaven2000** [binaryoutcast/binoc-central#76]
I uploaded the latest version of my Add-on Quickfolders 4.13.3 which specfically addresses 3 issues that only apply to Interlink. But apparently interlink die not pick up the fact that it was updated even when i click on the update menu i  Add-ons manager

**Comment by mattatobin** [comment]
I cannot confirm this. Are you using Interlink 6990?

**Comment by RealRaven2000** [comment]
Interlink updated to 6900 and it appeared to be fixed. I only installed Interlink around  2 weeks ago when a pale moon advocate contacted me about the new Add-on sharing panel, so that's when i set to work on converting 2 of my Add-ons. I will likely add my other mail Add-ons (quickFilters, SmartTemplate4, FiltaQuilla) soon, too.
One more thing that would be nice would be a version notes field during upload but i guess that's a new issue.

**Comment by RealRaven2000** [comment]
Interlink updated to 6900 and it appeared to be fixed. I only installed Interlink around  2 weeks ago when a pale moon advocate contacted me about the new Add-on sharing panel, so that's when i set to work on converting 4 of my Add-ons (three of them are mail compatible). 

I will likely add my other mail Add-ons (quickFilters, SmartTemplate4, FiltaQuilla) soon, too.
One more thing that would be nice would be a version notes field during upload but i guess that's a new issue.

**Comment by mattatobin** [comment]
Interlink has release notes on the website.

**Comment by Lootyhoof** [comment]
@RealRaven2000 is probably referring to release notes for add-ons on Phoebus - which is being tracked over at https://github.com/Pale-Moon-Addons-Team/phoebus/issues/97.

**Comment by mattatobin** [comment]
True, support for the Add-ons Site should be directed to the Phoebus repository.
