### ISSUE TITLE
Interlink doesn't follow system DPI scaling

### ISSUE THREAD

**Issue by hitokage004** [binaryoutcast/binoc-central#79]
The setting layout.css.devPixelsPerPx is set to 1.0 by default instead of -1.0 causing Interlink to not use/match the system DPI setting. Manually changing it resolves the issue.

Version 7025 on Windows 7

**Comment by mattatobin** [comment]
Your point?

**Comment by hitokage004** [comment]
It's not the default setting. I know this isn't Pale Moon (or anything else), but it's been set to automatic since PM24 - see https://forum.palemoon.org/viewtopic.php?t=3049

**Comment by mattatobin** [comment]
Is Interlink suddenly Pale Moon now? Am I Moonchild?

**Comment by hitokage004** [comment]
I only mentioned in case you didn't set it this way intentionally.

**Comment by mattatobin** [comment]
Except I did set it intentionally because I define what the default preferences are.

**Comment by hitokage004** [comment]
I only mentioned in case somehow it wasn't intentional - since I don't recall you having a HiDPPI display.

As you stated it's your project - at least it's documented here so know one else will bother you with it.

**Comment by mattatobin** [comment]
Nah, it really isn't.. Watch out for sparks!
