### ISSUE TITLE
Virtually all links on Arby's menu page fail to respond using EasyPrivacy in Pale Moon

### ISSUE THREAD

**Issue by lakrsrool** [binaryoutcast/binoc-central#80]
Here is the URL: https://arbys.com/our-menu/featured

If I use EasyPrivacy in ABPrime (updated to current version) then the website links do not work (URL above) -- links circled in the screen-shot below are  examples of what will not work when using EasyPrivacy in ABPrime.

ADDENDUM: I've discovered that this is only the case in Pale Moon --- using EasyPrivacy in ABPrime in Basilisk does not have this problem.  So for some reason if I disabled ABPrime or I just disable EasyPrivacy in ABPrime in Pale Moon then the problem is fixed in Pale Moon.  On the other hand I have no problem with using EasyPrivacy in ABPrime in the Basilisk browser.

So it's a combination of using EasyPrivacy in ABPrime in the Pale Moon browser that has the problem with the links on this website.  I've disabled EasyPrivacy in ABPrime in the Pale  Moon browser for now to use the website.

![none of links circle work with EasyPrivacy enabled](https://user-images.githubusercontent.com/37479799/56778738-b918bf80-678c-11e9-85c5-d45c02e1b42f.png)

**Comment by kn-yami** [comment]
This happens because EasyPrivacy list blocks Google Analytics and this website requires GA to function properly (it uses ES to handle links and the script will break if GA is blocked from loading). It does not work for me in Basilisk, Borealis and Pale Moon if I have the EasyPrivacy list enabled.
