### ISSUE TITLE
Application was unable to start Correctly (0x0000142)

### ISSUE THREAD

**Issue by velvetnsteel** [binaryoutcast/binoc-central#87]
I just installed 64bit Interlink email client Version 7176, to my Windows 10 version 1803 (build 17134.950) computer to give it a try..

Installs with no problem... but when attempting to open I get the 142 error code.

![interlink](https://user-images.githubusercontent.com/54743149/64064367-54ec8900-cbce-11e9-9953-0fe959bc3876.jpg)

**Comment by velvetnsteel** [comment]
I have also tried in compatibility mode using Windows 8, 7 and all 3 Vista choices... and still get the same error for all choices.

**Comment by mattatobin** [comment]
Read the System Requirements and Frequently Asked Questions... again.

**Comment by mattatobin** [comment]
Windows 10 doesn't like unsigned applications so it could be smartscreen or windows defender may have screwed over some of the files. Try the 32bit version. Seems to be more tollerent to that sometimes.

**Comment by velvetnsteel** [comment]
I read the system requirements..  
Windows Systems
Windows 7/Server 2008 R2 or newer
I read that to mean... Windows 7  "OR NEWER" versions of Windows..   I guess I was too logical.

**Comment by velvetnsteel** [comment]
I posted the issue thinking it was an Interlink issue that needs to be fixed.

Since Interlink is an ongoing project and Windows  7 is no longer supported by Microsoft... 
And, since Windows 10 has been around for 5 years  wouldn't both 32-bit and 64-bit versions be built to operate on Windows 10?

**Comment by velvetnsteel** [comment]
Followed the 32 bit suggestion..   32 bit does work on Windows 10.    Was surprised that the app emailed 2 of my email accounts and added the one email account to the app, all automatically without asking.

But thanks, I'll give it a try..   I have been using Fossamail for about 4-5 years after leaving Thunderbird.

**Comment by mattatobin** [comment]
Windows 7 EoL doesn't happen until next year. As for the rest of the stuff you said.. I have no idea what you are on about.

**Comment by mattatobin** [comment]
Win64 builds are access hardware somewhat differently than Win32 applications. That being said, Win32 builds are specifically built for maximum compatibility for JUST this sort of reason. If you can't run Win64 build because of a hardware or driver issue, then the recommended solution is run the Win32 version as you have done.

I will update the FAQ to reflect this.

NOTE: This has only ever cropped up on Windows 10. Price you pay for running a perpetually unfinished service AS an operating system, I guess.

**Comment by velvetnsteel** [comment]
I have been running Windows 10 since Preview build 9814 in 2014. ..  Never had any problem despite all the complaints I have heard from other people for the first few years after the public release...    Not that that means there is no problem now.

 Will get back to you and let you know if 1903 is any different when I upgrade in the next day or few days..    Thanks Mattatobin
